
[font]
size = 15
offset = { y = 1 }

[font.normal]
family = "Moralerspace Neon NF"
style = "Regular"

[window]
dimensions = { columns = 150, lines = 50 }
# decorations = "transparent"
decorations = "buttonless"
# decorations = "full"
# decorations = "none"
opacity = 0.85
blur = true
padding = { x = 5, y = 4 }
dynamic_padding = true

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Always"

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  { key = "Return", mods = "Command", action = "ToggleSimpleFullscreen" },
]

[general]
import = ["~/.config/alacritty/themes/afterglow.toml"]
