import = ["~/.config/alacritty/themes/afterglow.toml"]

[font]
size = 15
[font.normal]
family = "UDEV Gothic 35NF"
style = "Regular"

[window]
dimensions = { columns = 150, lines = 50 }
# decorations = "transparent"
decorations = "buttonless"
# decorations = "none"
opacity = 0.85
blur = true
padding = { x = 3, y = 3 }
dynamic_padding = true

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Always"

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  { key = "Return", mods = "Command", action = "ToggleSimpleFullscreen" },
]
